[package]
name = "functo_rs"
version = "0.0.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
itertools.workspace = true
