[package]
name = "qualified_do_proptest"
autotests = true
version = "0.0.0"
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
qualified_do.workspace = true
proptest.workspace = true
