[package]
name = "qualified_do"
version = "0.0.0"
license = "MIT"
edition = "2021"

[dependencies]
qualified_do_macro.workspace = true
functo_rs.workspace = true
itertools.workspace = true

[dev-dependencies]
either.workspace = true
